In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import os

In [54]:
features_df = pd.read_csv('LabeledData.csv', index_col='label', header=0)
data_df = pd.read_csv('TestData.csv', header=0, index_col=0)

In [55]:
print(features_df)

                       0         1         2         3          4         5  \
label                                                                         
Lavani          0.041197  5.246215  0.756234  0.857798  87.441172  0.038027   
Lavani          0.022393  5.952968  0.684569  1.466163  87.042359  0.021713   
Lavani          0.038930  5.209987  0.786378  0.713919  87.228998  0.039007   
Lavani          0.020993  6.122227  0.642724  2.178858  86.355677  0.015064   
Lavani          0.060425  4.628222  0.789587  0.604692  84.420080  0.037851   
...                  ...       ...       ...       ...        ...       ...   
NationalAnthem  0.039627  5.332924  0.796043  0.720849  86.598678  0.029123   
NationalAnthem  0.095713  4.008360  0.905102  0.222478  87.490396  0.088268   
NationalAnthem  0.069989  4.346523  0.918798  0.173212  87.930736  0.041330   
NationalAnthem  0.069251  4.445211  0.898940  0.239199  87.014793  0.048802   
NationalAnthem  0.061288  4.670256  0.886883  0.3147

In [56]:
print(data_df)

            Names         0         1         2         3          4  \
0     70-MFCC.csv  0.030387  5.795869  0.696378  1.813626  86.296528   
1     71-MFCC.csv  0.026718  5.783462  0.718850  1.304085  87.595207   
2     39-MFCC.csv  0.036465  5.424046  0.732246  1.072112  85.740403   
3     38-MFCC.csv  0.036962  5.254736  0.745766  0.783597  85.110152   
4    113-MFCC.csv  0.039054  5.248324  0.770309  0.773223  85.558166   
..            ...       ...       ...       ...       ...        ...   
111   87-MFCC.csv  0.065028  4.455411  0.900494  0.232543  86.885727   
112   14-MFCC.csv  0.040021  5.201349  0.752769  0.879492  84.813071   
113   15-MFCC.csv  0.043212  5.187392  0.780848  0.835627  85.003936   
114  100-MFCC.csv  0.031528  5.458152  0.800108  0.577981  88.281553   
115  101-MFCC.csv  0.040512  5.288478  0.763650  0.864980  85.399834   

            5         6         7         8  ...        110        111  \
0    0.023095  6.009681  0.678990  1.634665  ...  -3.557219  

In [57]:
features_df['label'] = features_df.index

In [58]:
print(features_df)

                       0         1         2         3          4         5  \
label                                                                         
Lavani          0.041197  5.246215  0.756234  0.857798  87.441172  0.038027   
Lavani          0.022393  5.952968  0.684569  1.466163  87.042359  0.021713   
Lavani          0.038930  5.209987  0.786378  0.713919  87.228998  0.039007   
Lavani          0.020993  6.122227  0.642724  2.178858  86.355677  0.015064   
Lavani          0.060425  4.628222  0.789587  0.604692  84.420080  0.037851   
...                  ...       ...       ...       ...        ...       ...   
NationalAnthem  0.039627  5.332924  0.796043  0.720849  86.598678  0.029123   
NationalAnthem  0.095713  4.008360  0.905102  0.222478  87.490396  0.088268   
NationalAnthem  0.069989  4.346523  0.918798  0.173212  87.930736  0.041330   
NationalAnthem  0.069251  4.445211  0.898940  0.239199  87.014793  0.048802   
NationalAnthem  0.061288  4.670256  0.886883  0.3147

In [59]:
from sklearn.model_selection import train_test_split

# Assuming the target column is named 'label'
X = features_df.drop('label', axis=1)
y = features_df['label']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

# Initialize classifiers
classifiers = {
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier()
}

# Train the models
for name, model in classifiers.items():
    model.fit(X_train, y_train)
    print(f"{name} model trained.")

c:\Users\agraw\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression model trained.
Decision Tree model trained.
Random Forest model trained.
Support Vector Machine model trained.
K-Nearest Neighbors model trained.


In [62]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# logreg = LogisticRegression(solver = 'saga', max_iter = 100000)
model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=200))

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
y_pred_train = model.predict(X_train)

accuracy_train = accuracy_score(y_train, y_pred_train)
f1_train = f1_score(y_train, y_pred_train, average = 'micro')
precision_train = precision_score(y_train, y_pred_train, average = 'micro')
recall_train = recall_score(y_train, y_pred_train, average = 'micro')
confusion_mat_train = confusion_matrix(y_train, y_pred_train, labels = ['MichaelJackson', 'BhavGeet', 'Lavani', 'AshaBhosle', 'NationalAnthem', 'KishoreKumar'])
print(f"LogisticRegression Classification Accuracy: {accuracy_train:.2f}")
print(f"LogisticRegression Classification F1 Score: {f1_train:.2f}")
print(f"LogisticRegression Classification Precision: {precision_train:.2f}")
print(f"LogisticRegression Classification Recall: {recall_train:.2f}")
print(confusion_mat_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average = 'weighted')
precision = precision_score(y_test, y_pred, average = 'weighted')
recall = recall_score(y_test, y_pred, average = 'weighted')
confusion_mat = confusion_matrix(y_test, y_pred, labels = ['MichaelJackson', 'BhavGeet', 'Lavani', 'AshaBhosle', 'NationalAnthem', 'KishoreKumar'])
print(f"LogisticRegression Classification Accuracy: {accuracy:.2f}")
print(f"LogisticRegression Classification F1 Score: {f1:.2f}")
print(f"LogisticRegression Classification Precision: {precision:.2f}")
print(f"LogisticRegression Classification Recall: {recall:.2f}")
print(confusion_mat)


LogisticRegression Classification Accuracy: 0.99
LogisticRegression Classification F1 Score: 0.99
LogisticRegression Classification Precision: 0.99
LogisticRegression Classification Recall: 0.99
[[118   0   0   0   0   0]
 [  0 113   0   1   0   0]
 [  0   1  59   2   0   0]
 [  0   0   0 104   0   0]
 [  0   0   0   0  92   0]
 [  0   0   0   0   0 142]]
LogisticRegression Classification Accuracy: 0.83
LogisticRegression Classification F1 Score: 0.83
LogisticRegression Classification Precision: 0.84
LogisticRegression Classification Recall: 0.83
[[29  0  0  1  0  0]
 [ 0 30  3  3  0  0]
 [ 2  1 11  5  1  1]
 [ 0  1  2 12  0  0]
 [ 0  1  2  1 19  1]
 [ 1  0  0  1  0 30]]


In [63]:
data_df

Names         0         1         2         3          4  \
0     70-MFCC.csv  0.030387  5.795869  0.696378  1.813626  86.296528   
1     71-MFCC.csv  0.026718  5.783462  0.718850  1.304085  87.595207   
2     39-MFCC.csv  0.036465  5.424046  0.732246  1.072112  85.740403   
3     38-MFCC.csv  0.036962  5.254736  0.745766  0.783597  85.110152   
4    113-MFCC.csv  0.039054  5.248324  0.770309  0.773223  85.558166   
..            ...       ...       ...       ...       ...        ...   
111   87-MFCC.csv  0.065028  4.455411  0.900494  0.232543  86.885727   
112   14-MFCC.csv  0.040021  5.201349  0.752769  0.879492  84.813071   
113   15-MFCC.csv  0.043212  5.187392  0.780848  0.835627  85.003936   
114  100-MFCC.csv  0.031528  5.458152  0.800108  0.577981  88.281553   
115  101-MFCC.csv  0.040512  5.288478  0.763650  0.864980  85.399834   

            5         6         7         8  ...        110        111  \
0    0.023095  6.009681  0.678990  1.634665  ...  -3.557219  -4.769600   
1    0.015774  6.516176  0.616081  2.963763  ...  -7.479678 -10.450026   
2    0.020270  6.131905  0.655356  1.843641  ...   0.200098  -8.081958   
3    0.044238  4.974656  0.777848  0.554718  ...  -7.051536  -9.983333   
4    0.021983  6.079378  0.686759  1.616327  ... -10.044515  -0.142227   
..        ...       ...       ...       ...  ...        ...        ...   
111  0.036575  5.333256  0.787555  0.653052  ...   3.123366   7.692238   
112  0.024313  5.922859  0.673797  1.594170  ...  -4.209217  -2.834459   
113  0.025487  5.933917  0.702359  1.616970  ...  -3.139267  -2.614198   
114  0.022508  5.948788  0.696189  1.222032  ...  -4.142894  -0.261467   
115  0.039342  5.218234  0.730137  0.879198  ...   1.040532   1.646498   

           112       113       114       115       116       117        118  \
0    -6.386009 -5.691897  0.075847 -1.245120  4.546164 -2.333128  10.077892   
1     2.245247 -3.452126 -1.930312 -6.825926 -0.462308 -3.562652  -2.894762   
2    -9.588246 -5.317054 -1.150022 -1.032335  5.748428  2.446726   3.189359   
3    -8.725751 -5.889359 -5.999659 -3.835344 -3.103641 -3.969246  -3.811548   
4     1.507162 -5.320269 -2.185936 -2.866291 -3.451173  1.482495   1.472503   
..         ...       ...       ...       ...       ...       ...        ...   
111 -14.131559  2.735633 -8.108873 -5.811838 -2.105190 -2.315753  -6.030786   
112   2.663685 -6.934862 -1.538460 -2.115241 -4.737934 -3.497907  -3.247443   
113  -5.999768 -6.341965  4.591229 -4.349581  8.819987 -3.838513   3.962640   
114  -3.065207 -3.913709 -3.554244 -2.941223 -2.252978 -2.266244  -3.469334   
115  -9.019209 -4.492607 -0.955646 -9.290629  1.344334 -4.568870  -9.240072   

          119  
0    3.306145  
1   -1.478166  
2   -2.178233  
3   -3.706002  
4   -0.900243  
..        ...  
111 -0.548713  
112 -6.286975  
113 -4.646894  
114 -5.127534  
115 -3.245940  

[116 rows x 121 columns]

In [64]:
labels = data_df['Names']
print(labels)
data_df = data_df.drop('Names', axis = 1)


0       70-MFCC.csv
1       71-MFCC.csv
2       39-MFCC.csv
3       38-MFCC.csv
4      113-MFCC.csv
           ...     
111     87-MFCC.csv
112     14-MFCC.csv
113     15-MFCC.csv
114    100-MFCC.csv
115    101-MFCC.csv
Name: Names, Length: 116, dtype: object


In [65]:
X_unlabeled = data_df.copy()

In [66]:
X_unlabeled.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '110', '111', '112', '113', '114', '115', '116', '117', '118', '119'],
      dtype='object', length=120)

In [67]:
# Predict the labels for the unlabeled data
y_pred_unlabeled = model.predict(X_unlabeled)

In [68]:
data_df['label'] = y_pred_unlabeled

In [69]:
print(data_df)

            0         1         2         3          4         5         6  \
0    0.030387  5.795869  0.696378  1.813626  86.296528  0.023095  6.009681   
1    0.026718  5.783462  0.718850  1.304085  87.595207  0.015774  6.516176   
2    0.036465  5.424046  0.732246  1.072112  85.740403  0.020270  6.131905   
3    0.036962  5.254736  0.745766  0.783597  85.110152  0.044238  4.974656   
4    0.039054  5.248324  0.770309  0.773223  85.558166  0.021983  6.079378   
..        ...       ...       ...       ...        ...       ...       ...   
111  0.065028  4.455411  0.900494  0.232543  86.885727  0.036575  5.333256   
112  0.040021  5.201349  0.752769  0.879492  84.813071  0.024313  5.922859   
113  0.043212  5.187392  0.780848  0.835627  85.003936  0.025487  5.933917   
114  0.031528  5.458152  0.800108  0.577981  88.281553  0.022508  5.948788   
115  0.040512  5.288478  0.763650  0.864980  85.399834  0.039342  5.218234   

            7         8          9  ...        111        112  

In [70]:
data_df['Names'] = labels


In [76]:
proba = model.predict_proba(X_unlabeled)
max_proba = np.max(proba, axis=1)
data_df['prob'] = max_proba

In [77]:
data_df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '113', '114', '115', '116', '117', '118', '119', 'label', 'Names',
       'prob'],
      dtype='object', length=123)

In [78]:
# Remove the label column from the DataFrame
# data_df.drop('label', axis=1, inplace=True)

# Save the predicted labels to a CSV file
data_df.to_csv('PredictedLabelsWithoutPCA.csv')

In [80]:
result_df = data_df[['Names', 'label', 'prob']]

In [81]:
result_df

Names           label      prob
0     70-MFCC.csv      AshaBhosle  0.761068
1     71-MFCC.csv      AshaBhosle  0.978359
2     39-MFCC.csv          Lavani  0.572196
3     38-MFCC.csv        BhavGeet  0.442725
4    113-MFCC.csv    KishoreKumar  0.929502
..            ...             ...       ...
111   87-MFCC.csv  NationalAnthem  0.999574
112   14-MFCC.csv    KishoreKumar  0.359290
113   15-MFCC.csv      AshaBhosle  0.999235
114  100-MFCC.csv    KishoreKumar  0.732054
115  101-MFCC.csv    KishoreKumar  0.692197

[116 rows x 3 columns]

In [82]:
result_df.to_csv('ResultDF.csv')

Asha Bhosle

In [85]:
filtered_df = result_df[result_df['label'] == 'AshaBhosle']
sorted_df = filtered_df.sort_values(by='prob', ascending = False)
sorted_df


Names       label      prob
58    99-MFCC.csv  AshaBhosle  0.999644
82    72-MFCC.csv  AshaBhosle  0.999494
113   15-MFCC.csv  AshaBhosle  0.999235
77    79-MFCC.csv  AshaBhosle  0.998640
41    22-MFCC.csv  AshaBhosle  0.998441
87    04-MFCC.csv  AshaBhosle  0.997887
103   68-MFCC.csv  AshaBhosle  0.996754
51   115-MFCC.csv  AshaBhosle  0.996637
109   62-MFCC.csv  AshaBhosle  0.994592
9     06-MFCC.csv  AshaBhosle  0.992381
100   91-MFCC.csv  AshaBhosle  0.992233
74   106-MFCC.csv  AshaBhosle  0.991728
5    112-MFCC.csv  AshaBhosle  0.991131
7     94-MFCC.csv  AshaBhosle  0.986702
1     71-MFCC.csv  AshaBhosle  0.978359
93    40-MFCC.csv  AshaBhosle  0.975360
94    41-MFCC.csv  AshaBhosle  0.965171
10    33-MFCC.csv  AshaBhosle  0.939819
72    80-MFCC.csv  AshaBhosle  0.929546
107   56-MFCC.csv  AshaBhosle  0.915332
60    42-MFCC.csv  AshaBhosle  0.913580
34    85-MFCC.csv  AshaBhosle  0.911726
70    12-MFCC.csv  AshaBhosle  0.889369
73   107-MFCC.csv  AshaBhosle  0.857652
25    25-MFCC.csv  AshaBhosle  0.819362
39   102-MFCC.csv  AshaBhosle  0.810984
106   57-MFCC.csv  AshaBhosle  0.801313
50    48-MFCC.csv  AshaBhosle  0.784673
43    54-MFCC.csv  AshaBhosle  0.769737
90    36-MFCC.csv  AshaBhosle  0.762762
0     70-MFCC.csv  AshaBhosle  0.761068
42   109-MFCC.csv  AshaBhosle  0.716721
32    60-MFCC.csv  AshaBhosle  0.698282
18    82-MFCC.csv  AshaBhosle  0.693429
46    77-MFCC.csv  AshaBhosle  0.591587
64    51-MFCC.csv  AshaBhosle  0.515758
27    52-MFCC.csv  AshaBhosle  0.501192
61    27-MFCC.csv  AshaBhosle  0.488911
83   110-MFCC.csv  AshaBhosle  0.449466
76    31-MFCC.csv  AshaBhosle  0.421550

In [86]:
filtered_df = result_df[result_df['label'] == 'KishoreKumar']
sorted_df = filtered_df.sort_values(by='prob', ascending = False)
sorted_df


Names         label      prob
91    09-MFCC.csv  KishoreKumar  0.999990
54    93-MFCC.csv  KishoreKumar  0.999602
35    84-MFCC.csv  KishoreKumar  0.999581
80    46-MFCC.csv  KishoreKumar  0.999553
68    65-MFCC.csv  KishoreKumar  0.998131
30    29-MFCC.csv  KishoreKumar  0.996665
66    18-MFCC.csv  KishoreKumar  0.993038
19    83-MFCC.csv  KishoreKumar  0.991757
63    50-MFCC.csv  KishoreKumar  0.981893
24    24-MFCC.csv  KishoreKumar  0.978370
23    58-MFCC.csv  KishoreKumar  0.977494
53    92-MFCC.csv  KishoreKumar  0.971297
11    32-MFCC.csv  KishoreKumar  0.960646
21    59-MFCC.csv  KishoreKumar  0.949963
99    02-MFCC.csv  KishoreKumar  0.932274
4    113-MFCC.csv  KishoreKumar  0.929502
14    67-MFCC.csv  KishoreKumar  0.920411
8     07-MFCC.csv  KishoreKumar  0.835260
65    19-MFCC.csv  KishoreKumar  0.817717
114  100-MFCC.csv  KishoreKumar  0.732054
89    37-MFCC.csv  KishoreKumar  0.714056
115  101-MFCC.csv  KishoreKumar  0.692197
45    55-MFCC.csv  KishoreKumar  0.665371
101   90-MFCC.csv  KishoreKumar  0.584161
108   63-MFCC.csv  KishoreKumar  0.580351
112   14-MFCC.csv  KishoreKumar  0.359290

In [87]:
filtered_df = result_df[result_df['label'] == 'MichaelJackson']
sorted_df = filtered_df.sort_values(by='prob', ascending = False)
sorted_df

Names           label      prob
49   114-MFCC.csv  MichaelJackson  0.999909
92    08-MFCC.csv  MichaelJackson  0.999234
78    78-MFCC.csv  MichaelJackson  0.998192
12    44-MFCC.csv  MichaelJackson  0.995792
13    45-MFCC.csv  MichaelJackson  0.990359
98    03-MFCC.csv  MichaelJackson  0.983023
38   103-MFCC.csv  MichaelJackson  0.980803
104   20-MFCC.csv  MichaelJackson  0.975018
55    34-MFCC.csv  MichaelJackson  0.972249
110   86-MFCC.csv  MichaelJackson  0.956539
95    74-MFCC.csv  MichaelJackson  0.925703
33    61-MFCC.csv  MichaelJackson  0.880585
26    53-MFCC.csv  MichaelJackson  0.592848
57    98-MFCC.csv  MichaelJackson  0.499570
56    35-MFCC.csv  MichaelJackson  0.471613
44   108-MFCC.csv  MichaelJackson  0.424682

In [89]:
filtered_df = result_df[result_df['label'] == 'NationalAnthem']
sorted_df = filtered_df.sort_values(by='prob', ascending = False)
sorted_df

Names           label      prob
37   16-MFCC.csv  NationalAnthem  0.999700
111  87-MFCC.csv  NationalAnthem  0.999574
96   75-MFCC.csv  NationalAnthem  0.998892
71   81-MFCC.csv  NationalAnthem  0.908467
6    95-MFCC.csv  NationalAnthem  0.904110
52   01-MFCC.csv  NationalAnthem  0.805935
36   17-MFCC.csv  NationalAnthem  0.560613

In [90]:
filtered_df = result_df[result_df['label'] == 'Lavani']
sorted_df = filtered_df.sort_values(by='prob', ascending = False)
sorted_df

Names   label      prob
31    28-MFCC.csv  Lavani  0.996987
79    47-MFCC.csv  Lavani  0.991579
62    26-MFCC.csv  Lavani  0.990976
81    73-MFCC.csv  Lavani  0.946701
75    30-MFCC.csv  Lavani  0.928277
102   69-MFCC.csv  Lavani  0.902045
67    64-MFCC.csv  Lavani  0.896634
17    11-MFCC.csv  Lavani  0.887682
29    89-MFCC.csv  Lavani  0.883615
59    43-MFCC.csv  Lavani  0.746832
69    13-MFCC.csv  Lavani  0.615651
20   104-MFCC.csv  Lavani  0.601549
2     39-MFCC.csv  Lavani  0.572196
48    49-MFCC.csv  Lavani  0.542781

In [91]:
filtered_df = result_df[result_df['label'] == 'BhavGeet']
sorted_df = filtered_df.sort_values(by='prob', ascending = False)
sorted_df

Names     label      prob
16    10-MFCC.csv  BhavGeet  0.999434
85    96-MFCC.csv  BhavGeet  0.985465
97   116-MFCC.csv  BhavGeet  0.985219
40    23-MFCC.csv  BhavGeet  0.972655
86    97-MFCC.csv  BhavGeet  0.838169
22   105-MFCC.csv  BhavGeet  0.798124
84   111-MFCC.csv  BhavGeet  0.778085
28    88-MFCC.csv  BhavGeet  0.666368
15    66-MFCC.csv  BhavGeet  0.628069
88    05-MFCC.csv  BhavGeet  0.557698
47    76-MFCC.csv  BhavGeet  0.529999
3     38-MFCC.csv  BhavGeet  0.442725
105   21-MFCC.csv  BhavGeet  0.395642